# Generated by Django 5.2.6 on 2025-09-26 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'STU'), ('Faculty', 'FAC'), ('Librarian', 'LIB'), ('Admin', 'ADM')], default='Student', max_length=50),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='FULL NAME')),
                ('usn', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='USN')),
                ('email', models.EmailField(max_length=254, verbose_name='EMAIL')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
