# Generated by Django 5.2.6 on 2025-09-27 09:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_librarian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Book Title')),
                ('author', models.CharField(max_length=255, verbose_name='Author')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('category', models.CharField(choices=[('SCI', 'Science'), ('ENG', 'Engineering'), ('LIT', 'Literature'), ('HIS', 'History'), ('TECH', 'Technology'), ('OTH', 'Other')], default='OTH', max_length=10, verbose_name='Category')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Publisher')),
                ('published_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Published Year')),
                ('total_copies', models.PositiveIntegerField(default=1, verbose_name='Total Copies')),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='Available Copies')),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Added to Library')),
            ],
        ),
        migrations.AlterField(
            model_name='librarian',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='libuser', to=settings.AUTH_USER_MODEL, verbose_name='USER'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='alloted_books_by_faculty', to='core.book', verbose_name='Books'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='alloted_books_by_std', to='core.book', verbose_name='Books'),
            preserve_default=False,
        ),
    ]
