# Generated by Django 5.2.6 on 2025-09-27 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_book_alter_librarian_user_faculty_book_student_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alloted_books_by_faculty', to='core.book', verbose_name='Books'),
        ),
        migrations.AlterField(
            model_name='student',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alloted_books_by_std', to='core.book', verbose_name='Books'),
        ),
    ]
