# Generated by Django 5.2.6 on 2025-09-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bookrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='book',
        ),
        migrations.RemoveField(
            model_name='student',
            name='book',
        ),
        migrations.AddField(
            model_name='faculty',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, related_name='alloted_books_by_faculty', to='core.book', verbose_name='Books'),
        ),
        migrations.AddField(
            model_name='student',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, related_name='alloted_books_by_std', to='core.book', verbose_name='Books'),
        ),
    ]
