# Generated by Django 5.2.6 on 2025-09-30 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_faculty_book_remove_student_book_faculty_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='book',
            field=models.ManyToManyField(blank=True, related_name='alloted_books_by_faculty', to='core.book', verbose_name='Books'),
        ),
        migrations.AlterField(
            model_name='student',
            name='book',
            field=models.ManyToManyField(blank=True, related_name='alloted_books_by_std', to='core.book', verbose_name='Books'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('message', models.TextField(max_length=1000, verbose_name='Message')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
